### ISSUE TITLE
Can i know what does find_response function do?

### ISSUE THREAD

**Issue by ftimahazza** [div3125/k-nearest-neighbors#4]
Can you elaborate more on the function find_response? And can i know how to calculate the accuracy for this prediction? Thank you in advance.

**Comment by ParallelDiv** [comment]
`find_response()` selects the most occurring class from the K nearest neighbors for each sample in the test set. For each sample in the test_set, it gets a list of classes that are the K-nearest neighbors of that particular sample.

Let's say you have 10 classes **a,b,c,...,j** and your **K** is 7, so you are performing 7-NearestNeighbors. Our list of classes then becomes **["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"]**.

For a particular instance in the test set, let's assumen you get 7 nearest neighbors as **["a", "a", "g", "a", "g", "e", "c" ]**. On counting total votes (number of occurrences) for each class we get:

**a** -> 3
**c** -> 1
**e** -> 1
**g** -> 2

Based on that, the most occurring class is **a** with 3 votes, and that becomes our prediction. The function which calls `find_response()`, `knn()` maintains a list of all classes. `find_response()` will return two values, the first one is the index of the predicted class from this list, and the second value is the total number of votes this class got, which is 3 in our case.

This code does not have a method of calculating test accuracy. I think you'll have to modify `knn()` or implement a separate function to read test classes and count the total number of predictions that match with them to calculate accuracy.

**Comment by ftimahazza** [comment]
Thank you for the explanation ☺️.
